import Head from "next/head";
import { Dispatch, SetStateAction, useEffect, useState } from "react";

export default function Home() {
  const [stackLeft, setStackLeft] = useState<number[]>([1, 2, 3]);
  const [stackMiddle, setStackMiddle] = useState<number[]>([]);
  const [stackRight, setStackRight] = useState<number[]>([]);

  useEffect(() => {
    console.log(stackLeft);
    console.log(stackMiddle);
    console.log(stackRight);
  }, [stackLeft, stackMiddle, stackRight]);

  const move = (
    dispatchFrom: Dispatch<SetStateAction<number[]>>,
    dispatchTo: Dispatch<SetStateAction<number[]>>
  ) => {
    dispatchFrom((prev) => {
      if (prev.length === 0) return [];

      const poppedItem = prev[0] ?? 0;
      dispatchTo((prev) => [...prev, poppedItem]);
      return prev.slice(1);
    });
  };

  const validateMove = (stackFrom: number[], stackTo: number[]) => {
    if (stackFrom.length === 0) return false;
    const fromItem = stackFrom[0];
    const toItem = stackTo[0];
    return !toItem || !fromItem || fromItem < toItem;
  };

  return (
    <>
      <Head>
        <title>Tower of Hanoi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main>
    </>
  );
}
